[build]
  command = "npm install && npm run typecheck && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 